### ISSUE TITLE
Enabling Display Suite Format module produces error 

### ISSUE THREAD

**Issue by philsward** [backdrop-contrib/ds#6]
When enabling the **Display Suite Format** module, the following error is produced:

```
PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'user_backdropdb.filter_format' doesn't exist: SELECT 1 FROM {filter_format} WHERE format = :format LIMIT 0, 1; Array ( [:format] => ds_code ) in ds_format_enable() (line 12 of /home/user/public_html/t/sandbox/backdrop1.sandbox/modules/ds/modules/ds_format/ds_format.install).

DismissSQLSTATE[42S02]: Base table or view not found: 1146 Table 'user_backdropdb.filter_format' doesn't exist: SELECT 1 FROM {filter_format} WHERE format = :format LIMIT 0, 1; Array ( [:format] => ds_code )
```

This appears to be caused from Backdrop moving the filter formats to the config code instead of using the database.

I don't use this module. Just reporting the problem. I will do what I can to help test if fixes become available.

**Comment by hosef** [comment]
This has been fixed in this commit:
https://github.com/backdrop-contrib/ds/commit/45fa19552d9b8f4d2352f36c70eac9afffce3be3
