### ISSUE TITLE
PHP error when using multi-column layouts

### ISSUE THREAD

**Issue by philsward** [backdrop-contrib/ds#7]
Setting any layout to something other than **One column** and **Reset** on a form (Manage Fields admin page) using the **Display Suite Forms** module causes the following error on page creation / edit:

```
Warning: implode(): Invalid arguments passed in include() (line 13 of /home/user/public_html/t/sandbox/backdrop1.sandbox/modules/ds/layouts/ds_2col_fluid/ds-2col-fluid.tpl.php).
```

Note the error only depicts the 2-col-fluid layout, however I did check and all of the other multi-column layouts suffer from this same error.

I do not use this sub-module. Just reporting the problem. I will do what I can to help with testing.

**Comment by hosef** [comment]
@philsward I think i have this fixed, so if you can test the latest dev version, that would be great.

**Comment by philsward** [comment]
No longer getting the error when switching the DS layouts on the Manage Fields page. I'd say the fix is good but it does make me wonder why it was there in the first place and what else might break from the removal of the implode.

The errors are gone so that's good. If it causes other issues, I suppose those can be sorted out later.
